# Header
menu:
  存档: /archives

# Content
categoryimg:
  人: /images/categories/f11f3a292df5e0fe282658245f6034a85edf72dd.jpg
  梦: /images/categories/P1180011.JPG
  思: /images/categories/IMGP3079x.jpg
  回忆: /images/categories/P1040600.jpg
coverimg: /images/cover.jpg
  
# Miscellaneous
favicon: /favicon.png
sitename: fanjun.name

# search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
