# Header
menu:
  存档: /archives

# Content
categoryimg:
  人: /images/categories/f11f3a292df5e0fe282658245f6034a85edf72dd.jpg
  梦: /images/categories/P1180011.JPG
  思: /images/categories/IMGP3079x.jpg
  回忆: /images/categories/P1040600.jpg
  纹章: /images/categories/Nord-Tifosi_2018-1024x683.jpg
coverimg: /images/cover.jpg
  
# Miscellaneous
favicon: /favicon.png
sitename: fanjun.name

#Valine
valine: true
v_appId: Bos1CI2DxVm7dWTz4jMielJa-gzGzoHsz
v_appKey: 8uiwUjptLPmW3mApTFrDlYjj
